# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:categories/:year-:month-:day-:title/


# Setup
title:            Putri's Site
tagline:          ''
description:      'Academic and Teaching Portfolio'
url:              'https://agustinosputri.github.io'
baseurl:          /

author:
  name:           'Putri Agustinos'


paginate:         5
paginate_path:    "/blog/page:num/"

# Sass settings
sass:
  sass_dir: assets/css/_scss
  style: compressed

# Full URL for indexing
# url: https://agustinosputri.github.io

#Google Services
#google_analytics:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-pdf-embed

# Markdown
kramdown:
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  work:
    output: true 
    permalink: work/:path/
  tags:
    output: true 
    permalink: tag/:path/

# Excludes
exclude:
  - CNAME
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock


# Default Settings
defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false  # Hide metadata for all pages
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: phlow     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: phlow     # Default author for posts
