# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Putri Agustinos E-Portfolio
tagline:          'Academic and Teaching Portfolio'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> a digital hub for academic and teaching portfolio. Made by <a href="https://twitter.com/putriagustinos" target="_blank">@putriagustinos</a>.'
url:              'agustinosputri.github.io'
baseurl:          /

author:
  name:           'Putri Agustinos'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agustinosputri
